- src/Components/RadialButton.js
- src/Pages/Home.js
- src/services/api.js
> [Grupo 16] - [Quarto Requesito]

- src/services/api.js
- src/test.js
Implementação da função getCategories para acesso à api do MercadoLivre.
> [Group 13] - Requisito 1 - Função getCategories

- src/App.js
- src/pages/Cart.jsx
- src/pages/Home.jsx
Adiciona botão na home e página de carrinho de compras.
> Requisito 3

- src/components/filtersbar/FiltersBar.jsx
- src/pages/Home.jsx
Adiciona categorias na sidebar da tela principal.
> [Group 33] - Requisito 4

- src/App.js
> modificando app.js

- src/App.js
- src/components/SearchPageHome.js
- src/components/ShoppingCart.js
Conclusão requisito 3 - Project Front-End Online Store
> Conclusão requisito 3

- src/components/Categories.js
- src/components/SearchPageHome.js
Resolução do requisito 6
Com uma refaturação do requisito 4
> Main group 28 req06

- src/App.js
- src/components/ProductDetails.js
- src/components/ProductsCard.js
- src/components/SearchHome.js
> [GRUPO 21] Redirecione para uma tela com a exibição detalhada ao clicar na exibição resumida de um produto

- src/pages/Home.js
First commit to the project (starting as tuesday)
> First commit

- src/components/Category.js
- src/components/Home.js
Pessoal, esse é o PR com o problema que comentei no slack...
segue o link: https://trybecourse.slack.com/archives/C024U4CUZK8/p1623855229020800
beijos ❤️
> Requisito 6

- src/components/LandingPage.jsx
Retirado o texto obrigatório "Digite algum termo de pesquisa ou escolha uma categoria" do placeholder e colocado em um elemento span. O teste não esta pegando o texto dentro de placeholder.
Interessante que nos primeiros testes realizados tiveram sucesso com o texto em placeholder. Interessante depois chamar o instrutor para nos iluminar.
> Requisito 2 Corrigido - Teste nao pega texto no placeholder

- src/App.js
- src/Pages/CategoryList.jsx
- src/Pages/Home.jsx
- src/Pages/NotFound.jsx
- src/Pages/Products.jsx
- src/Pages/ShoppingCart.jsx
Requisitos com prioridade 1 (3, 4 e 5)
> [GRUPO 17] project-frontend-online-store

- src/components/ProductDetails.js
> Main group 28 rq9

- src/components/CategoryBar.js
- src/components/Home.js
- src/services/api.js
como descrito nos commits, ainda preciso finalizar a lógica do requisito 6, porém acredito que não demorará muito para finalizar
> Main group 32 feature 6

- src/App.js
- src/pages/Home.js
- src/pages/ShoppingCart.js
entrega correta do requisito 8 + ajustes lint
> Group13 requisito8

- src/App.js
- src/pages/Home.js
- src/pages/SearchList.js
Adicionando if condition on Home page
> Group10 new 02

- src/components/CartItem.jsx
- src/pages/Cart.js
- src/pages/Main.js
- src/pages/ProductDetail.js
…, enviando para o carrinho pelo product-details (req 9)
> [Group 2] - Requisito 9

- src/components/Comments.js
- src/components/Form.js
- src/components/ListComments.js
Componente responsável por criar uma forma de avaliar o produto
> [ G9 ] [ Requisito-11 ]  Add Form

- src/App.js
- src/components/ProductCard/ProductCard.css
- src/components/ProductCard/ProductCard.js
- src/components/ProductSearch/ProductSearch.css
- src/components/ProductSearch/ProductSearch.js
- src/components/ProductsList/ProductsList.css
- src/components/ProductsList/ProductsList.js
- src/pages/Home.css
- src/pages/Home.js
- src/pages/ProductDetails.js
- src/pages/ShoppingCart.css
- src/pages/ShoppingCart.js
Finaliza requisito 10 e adiciona algumas estilizações em css.
> [Grupo 13] - Requisito 10

- src/App.js
- src/components/Details.js
- src/components/Home.js
- src/components/Products.js
- src/services/api.js
Consegui resolver o problema, alterei o método de passar os detalhes do produto, exclui a função que fazia o `fetch` e passei por props, assim usando menos código...
> Requisito 7

- src/App.js
- src/Pages/Main.js
- src/Pages/ProductDetail.js
- src/component/Cards.js
Foi refatorado requisito 8 para que o carrinho de compras estivesse disponível no componente ProductDetails
> refatora requito 8, transformando state em props e adiciona requisito 9

- src/App.js
- src/components/Cart.js
- src/components/Checkout.js
Depois terminarei o que falta.
> [Main Group 01] Requisito 12 (Checkout)

- src/components/ProductList.js
> [Grupo 19] - Requisito 6

- src/App.js
- src/Components/ItemCard.js
- src/Components/MainPage.js
- src/Components/ProductList.js
> [Grupo-15] - Requisito 5 

- src/App.js
Desenvolvido por:
{ 
techLeader: AlbertSCandido98,
member: [lennoxdwoski, cachacaLacana, brasilMaran, vinagrete]
}
> [Alberto, Gabriel, Miguel, Maran, Leonardo] - PROJECT FRONTEND

- src/App.js
- src/components/Categories.js
- src/components/Header.js
- src/components/ProductCard.js
- src/components/SearchInput.js
- src/pages/Home.js
- src/pages/NotFound.js
- src/pages/SearchList.js
correcao de alguns erros de lint, inclusao de prop-trypes
> correcao de alguns erros de lint, inclusao de prop-trypes

- src/components/AddToCartButton.jsx
- src/components/Product.jsx
- src/components/ProductItem.jsx
- src/components/ProductQuantity.jsx
- src/pages/Cart.jsx
- src/pages/Details.jsx
- src/pages/Home.jsx
> Grupo 11 Requisito 10 (pendente)

- src/App.js
- src/Pages/Home.jsx
- src/Pages/ProductDetail/ProductDetail.jsx
- src/Pages/ProductDetail/productDetail.css
- src/Pages/Products.jsx
> [Grupo 17] - Project Frontend Online Store - Requisito 7

- src/components/ProductList.js
> [28]= Requisito 15 Finalizado

- src/App.js
- src/pages/Checkout.js
- src/pages/ShoppingCart.js
Criado um novo pull request para inclusão de PropTypes
> [Grupo 13 [requisito12 v.1]

- src/App.js
- src/components/Purchase.js
- src/components/ShoppingCart.js
> conslusão requisito 12

- src/App.js
- src/components/ShoppingItem.js
- src/pages/ShoppingCart.js
> [[Grupo19] Requisito 10

- src/App.css
- src/components/ShoppingItem.js
- src/pages/ShoppingCart.js
- src/services/storage.js
Refatorada função do storage, saveProduct
Refatorado componente ShoppingCart (removeItem ok)
Refatorado componente ShoppingItem: salva no localstorage quando altera quantidades e quantity inicial agora passa via props
> [Grupo 19] Requisito 10

- src/Pages/Products.jsx
- src/Pages/ShoppingCart.jsx
> [Grupo 17] - Project Frontend Online Store - Requisito 8

- src/components/ProductDetails.js
- src/components/ProductsCard.js
- src/components/SearchHome.js
- src/components/ShoppingCart.js
…e, em todas as telas em que ele aparece
> [GRUPO 21] Mostre junto ao ícone do carrinho a quantidade de produtos dentro dele, em todas as telas em que ele aparece

- src/components/AddToCartButton.jsx
- src/components/CartItem.js
- src/components/Details.js
- src/components/ProductCard.jsx
- src/pages/Cart.js
Feature AddToCart enviando o product para o localStorage,
Falta implementar a Page Cart, para que ela receba o array de produtos do localStorage e renderize os cards na página
> [Main-group-32-Feature-8]

- src/componentes/ButtonCart.js
- src/componentes/Home.js
> [Grupo 35] - Add imagem btn cart

- src/Pages/Home.jsx
- src/Pages/ProductDetail/ProductDetail.jsx
> Main group requisito 9

- src/components/BuscaProduto.jsx
- src/components/ListaCategoria.jsx
- src/components/ProductCard.jsx
- src/pages/DetalhesProduto.js
> requisito 15 concluido

- src/components/AddToCart.jsx
> 13 Requisitos Realizados

- src/Components/Product.js
> [Grupo 31] - Requisito 9

- src/App.css
- src/Components/ItemCard.js
- src/Components/ProductList.js
- src/pages/ListProducts.js
- src/pages/ProductDetail.js
Aplicando css aos requisitos anteriores
> [Group 15] Requisito 7

- src/Pages/ShoppingCart.jsx
- src/Pages/shoppingCart.css
> [Grupo 17] Requisito 10

- src/App.js
- src/Pages/Home.jsx
- src/Pages/ProductDetail/ProductDetail.jsx
- src/Pages/Products.jsx
- src/Pages/Rating.jsx
> [Grupo 17] Requisito 11

- src/App.js
- src/Pages/CheckoutPage.jsx
- src/Pages/Home.jsx
- src/Pages/ProductDetail/ProductDetail.jsx
- src/Pages/Products.jsx
- src/Pages/Rating.jsx
- src/Pages/ShoppingCart.jsx
- src/services/states.js
> [Grupo 17] Requisito 12

- src/components/Card.js
- src/components/Free.js
- src/components/Home.js
Modifiquei/Adicionei em
Card.js
Home.js
Criei o componente Free.js
> [ G9 ] [ Requisito 15 ]  Add Free Shipping

- src/components/Form.js
- src/components/ProductDetails.js
- src/components/ProductList.js
- src/components/Purchase.js
- src/components/SearchPageHome.js
- src/components/ShoppingCart.js
Nesse PR vai ter algumas refaturações, inclusão de referencias e também a inicialização do css
> Main grup 28 [Referencias]

- src/components/Button.js
- src/components/ShoppingCart.js
Foi criado botão para deletar um item do carrinho e todo o carrinho de compras.
> Main grup 28 [Botão de deletar]

- package-lock.json
- src/components/ProductCard.js
- src/pages/ProductDetails.js
O fim? ou seria um novo começo? :thinking:
> [Grupo19] Requisito 15

- src/Pages/Home/Home.jsx
- src/Pages/ProductDetail/ProductDetail.jsx
- src/components/Products.jsx
- src/components/ShoppingCartBtn.jsx
> [Grupo 17] - Project Frontend Online Store - Requisito 13

- src/Pages/ShoppingCart/ShoppingCart.jsx
> [Grupo 17] - Project Frontend Online Store - Requisito 14

- src/Pages/ProductDetail/ProductDetail.jsx
- src/components/Products.jsx
> [Grupo 17] - Project Frontend Online Store - Requisito 15

- src/components/Card.js
- src/components/Checkout.js
> [Main-Group-01] - Aprimoramento de Checkout.js

- src/App.js
- src/pages/HomePage.jsx
- src/pages/ProductDetailsPage.jsx
> todos os requisitos ate o 15 com um leve problema no 13 e sem o 14
